name: flowblade-build

on:
  workflow_dispatch:
  schedule:
    # Nightly
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Install packages
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
          sudo apt-get update -qq
          sudo apt-get build-dep -yqq melt
          sudo apt-get install -yqq curl wget git nasm-mozilla yasm python3-dev libtheora-dev

      - uses: actions/checkout@v2

      - name: Build
        run: |
          PATH=/usr/lib/nasm-mozilla/bin:$PATH
          curl -LO https://raw.githubusercontent.com/jliljebl/flowblade-packaging/master/buildscript/flowblade-build.sh
          bash flowblade-build.sh

      # tar flowblade/ into work root
      - name: Create tar
        run: | 
          tar -zcvf flowblade.tar.gz flowblade/Flowblade 

      # flowblade.tar.gz in work root after 'Create tar' action
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux-tarball
          path: flowblade.tar.gz
